
services:
  backend:
    container_name: mamilha_backend
    build:
      context: .
      dockerfile: backend/dockerfile
    volumes:
      - ./backend/db.sqlite3:/app/backend/db.sqlite3
      - /backend:/app
    ports:
      - "8000:8000"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
