version: '3'

services:
  backend:
    container_name: mamilha_backend
    build:
      context: .
      dockerfile: backend/dockerfile
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
      - ./backend/secrets.json:/app/secrets.json
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
