# Generated by Django 4.2.12 on 2024-07-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='deleted',
            field=models.BooleanField(default=1),
        ),
    ]
