# Generated by Django 4.2.12 on 2024-07-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
