# Generated by Django 4.2.12 on 2024-10-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_category',
            name='icon',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='group_category',
            name='icon_color',
            field=models.CharField(default='', max_length=10),
        ),
    ]
