# Generated by Django 4.2.12 on 2024-11-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_member_unique_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='color',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='grades',
            name='expense',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='grades',
            name='group',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='grades',
            name='member',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='grades',
            name='view_expense',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='grades',
            name='view_setting',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='grades',
            name='visible',
            field=models.BooleanField(default=0),
        ),
    ]
