# Generated by Django 4.2.12 on 2024-11-10 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.member'),
        ),
        migrations.AddField(
            model_name='finance',
            name='finance_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.financecategory'),
        ),
        migrations.AddField(
            model_name='finance',
            name='finance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.financetype'),
        ),
        migrations.AddField(
            model_name='finance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AddField(
            model_name='finance',
            name='pay_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.paymethod'),
        ),
        migrations.AddField(
            model_name='finance',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.member'),
        ),
        migrations.AddField(
            model_name='finance',
            name='split_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.splitmethod'),
        ),
    ]
