# Generated by Django 4.2.12 on 2024-07-05 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_deleted'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.member'),
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.finance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.member')),
            ],
        ),
    ]
