# Generated by Django 4.2.12 on 2024-07-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_finance_payer_split'),
    ]

    operations = [
        migrations.RenameField(
            model_name='split',
            old_name='user',
            new_name='member',
        ),
    ]
