# Generated by Django 4.2.12 on 2024-11-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financecategory',
            name='finance_type_id',
            field=models.IntegerField(choices=[(1, '지출'), (3, '이체')], default=1),
        ),
        migrations.AlterField(
            model_name='finance',
            name='title',
            field=models.TextField(),
        ),
    ]
