# Generated by Django 4.2.12 on 2024-11-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_financecategory_icon_financecategory_icon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='financecategory',
            name='finance_type_id',
            field=models.IntegerField(choices=[(1, '지출'), (3, '이체')], default=1),
        ),
    ]
